apiVersion: v1
kind: Secret
metadata:
  name: private-modern-data-stack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/cesarofuchi/k8s-modern-data-stack.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----