apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/cesarofuchi/k8s-modern-data-stack.git'    
    path: infra/src/helm-charts/minio-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'docker-desktop'
      namespace: deepstorage
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
